# Header
menu:
  Home: /
  About: /about
  Archives: /archives

social:
  twitter: https://twitter.com/
  github: https://github.com/
  instagram: https://twitter.com/
  weibo: https://weibo.com/

# Site favicon
favicon: /favicon.png

# Author avatar
avatar: /avatar.png